name: 'Create Project Card for New PR'

on:
  pull_request_target:
    # eventually we'll want to have workflows to manage several possible events on PRs
    # the full list is here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    types: [ opened ]

env:
  # this token must have typical repo write access plus full :project access
  # Create this token with the correct permissions and add it as a repo secret
  GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}

jobs:
  create-card:
    runs-on: ubuntu-latest
    steps:
      # check out the repo
      - uses: actions/checkout@v1
      # gets the current PR and stores it in a variable
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      # adds the variable to the environment so that we can use it in the next step
      - run: echo "PR=${{ steps.findPr.outputs.pr }}" >> $GITHUB_ENV
      # executes our bash script which could have more logic in it based on the event we are currently handling
      - run: bash add_to_project.sh ${{ env.PR }}
