name: 'Add PR to Project Create card'
on:
  pull_request_target:
    types: [ opened ]
#
jobs:
  create-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - run: echo "PR=${{ steps.findPr.outputs.pr }}" >> $GITHUB_ENV
      - run: echo "I must be on PR ${{ env.PR }}"
      - run: bash add_to_project.sh
