name: WarningTesting

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Issue Warning
      run: echo "::warning file=README.md,line=1,col=2::Problem"
 
    - name: Issue Error
      run: echo "::error file=app.js,line=10,col=15::Something went wrong"
